name: scrna-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - nextflow>=22.04.0
  - fastqc=0.11.9
  - multiqc=1.13
  - r-base=4.2
  - r-seurat=4.3
  - r-ggplot2=3.4
  - r-dplyr=1.1
  - r-rmarkdown=2.20
  - r-knitr=1.42
  - awscli=2.11
  - pip
  - pip:
    - boto3>=1.26.0
    - pandas>=1.5.0
    - numpy>=1.23.0
    - matplotlib>=3.6.0
    - seaborn>=0.12.0